### ISSUE TITLE
Practica5_MariaJoseLopezLeyva_4US

### ISSUE THREAD

**Issue by MariaJose-10** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-MariaJose-10#2]
[TOPICOS AVANZADOS_PRACTICA 5_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-MariaJose-10/files/8338160/TOPICOS.AVANZADOS_PRACTICA.5_MARIA.JOSE.LOPEZ.LEYVA.pdf)
[APP.zip](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-MariaJose-10/files/8338300/APP.zip)

**Comment by RaelRGB** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
